### ISSUE TITLE
Issue with the module

### ISSUE THREAD

**Issue by de-luxe110** [CharlieFuu69/RenPy_RhythmBeats#30]
Hello! I stumbled upon your code for the rhythm game system and was trying to implement it on my project since yours was the most fitting for my game. I tried it on a blank project and I am getting this error upon loading your the module. I copied the code in the documentation to a tee but it just doesn't work it seems. I don't know how to fix this issue since I don't speak Spanish nor can I find you anywhere for help. If you could drop your Discord, maybe we could chat about it, thanks.

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    call screen note_waterfall ## Muestra la cascada de notas
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/script.rpy", line 32, in execute
    screen stage_hud():
  File "game/script.rpy", line 32, in execute
    screen stage_hud():
  File "game/script.rpy", line 37, in execute
    if my_instance.is_running():
  File "game/script.rpy", line 40, in execute
    if my_instance.miss < 15:
  File "game/script.rpy", line 42, in execute
    vbox:
  File "game/script.rpy", line 44, in execute
    text "Notas acertadas: %s" % (my_instance.perfect + my_instance.great)
  File "game/script.rpy", line 44, in <module>
    text "Notas acertadas: %s" % (my_instance.perfect + my_instance.great)
AttributeError: 'RhythmPlayground' object has no attribute 'great'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    call screen note_waterfall ## Muestra la cascada de notas
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\exports.py", line 3345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 3579, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 4052, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 4052, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 32, in execute
    screen stage_hud():
  File "game/script.rpy", line 32, in execute
    screen stage_hud():
  File "game/script.rpy", line 37, in execute
    if my_instance.is_running():
  File "game/script.rpy", line 40, in execute
    if my_instance.miss < 15:
  File "game/script.rpy", line 42, in execute
    vbox:
  File "game/script.rpy", line 44, in execute
    text "Notas acertadas: %s" % (my_instance.perfect + my_instance.great)
  File "game/script.rpy", line 44, in <module>
    text "Notas acertadas: %s" % (my_instance.perfect + my_instance.great)
AttributeError: 'RhythmPlayground' object has no attribute 'great'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
rhythm test 1.0
Wed Nov 29 22:29:51 2023
```

**Comment by de-luxe110** [comment]
Hello, are there any updates to the module?

**Comment by CharlieFuu69** [comment]
Due to lack of time (due to my work) I have not been able to directly address the problem, but now that I review it patiently, the error points to critical attributes of the module.

![image](https://github.com/CharlieFuu69/RenPy_RhythmBeats/assets/77955772/dee1f73f-247c-4949-a62d-f0bfb25c67d2)

The indicated attributes are responsible for accounting for the playing of the notes or their failure, and for some reason (clearly my fault), these attributes are NOT present in the module.

Since I have made minute changes to the code of this module, outside the context of the project, I have to update several things (including the documentation).

My commitment is to have the update ready with the errors fixed by next Saturday (Dec 30).

---

> _This Issue will remain active until the update takes effect in this repository._

**Comment by CharlieFuu69** [comment]
@de-luxe110 Update `v1.07.0b` released.

Check the changes and download the new version at **[Release v1.07.0b_module](https://github.com/CharlieFuu69/RenPy_RhythmBeats/releases/tag/v1.07.0b_module)**.

Sections 3 and 4 of the documentation have received changes. Please review the changes made to the example code... and enjoy!

> _**[NOTE]:** Roadmap finished. This issue will be marked as closed._

**Comment by de-luxe110** [comment]
Thank you so much for the update, however I am still getting an error with just the regular code in the updated documentation. Here is the traceback.

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script
    python:
  File "game/script.rpy", line 81, in <module>
    my_instance = RhythmPlayground(
RhythmBeatsException: Beatmap read error: TypeError("a bytes-like object is required, not 'str'")

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script
    python:
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 81, in <module>
    my_instance = RhythmPlayground(
  File "game/rbs_plugin_alt.rpym", line 298, in __init__
  File "game/rbs_plugin_alt.rpym", line 340, in load
RhythmBeatsException: Beatmap read error: TypeError("a bytes-like object is required, not 'str'")

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
rhythm test 1.0
Tue Jan  2 18:22:55 2024
```
